.github/release-drafter.yml, .github/workflows/create-major-tag.yml, .github/workflows/release-drafter.yml, .github/workflows/required-labels.yml, README.md, docs/RELEASE.md
See the [RELEASE.md](https://github.com/elastic/oblt-actions/blob/feature/release/docs/RELEASE.md) file.
Tested in https://github.com/unelastisch/release-example/releases
=> Add release flow workflows

.github/workflows/test-google-auth.yml, google/auth/README.md, google/auth/action.yml
Adds the `google/auth` action — an opinionated action to authenticate with the elastic-observability GCP project.
=> Add google/auth action

.github/workflows/test-oblt-cli-cluster-create-serverless.yml
Fix evaluation of `dry-run` input.
use `github.event.inputs.dry-run` if it is defined, else `true`
=> Fix dry-run input

.github/workflows/no-test.yml, .github/workflows/test-check-dependent-jobs.yml, check-dependent-jobs/README.md, check-dependent-jobs/action.yml
will be handy for testing in this repo where the `test` status check is expected
=> Add check-dependent-jobs action

.pre-commit-config.yaml
Updating to `v0.3.1` should fix markdown tables with multiline strings.
=> Update action-readme pre-commit hook

oblt-cli/cluster-create-ccs/README.md, oblt-cli/cluster-create-custom/README.md, oblt-cli/cluster-create-serverless/README.md
Remove usage of `elastic/oblt-actions/google/auth` in docs where it's not necessary to avoid confusion.
=> Remove google/auth usage in oblt-cli/create-* actions

oblt-cli/run/action.yml
Make the oblt-cli/run action work the same way as in [apm-pipeline-library](https://github.com/elastic/apm-pipeline-library/blob/ddbd11ec95509883f8bf60b7bb0da1a6610b603a/.github/actions/oblt-cli/action.yml#L29).
This is a potential security risk that we need to tackle in a follow-up. But for the sake of migration, I will revert to the original behaviour.
We should be good if we do not use untrusted inputs in the command.
=> Fix oblt-cli/run action

.github/workflows/test-buildkite-run.yml, .github/workflows/test-oblt-cli-cluster-create-custom.yml, .github/workflows/test-oblt-cli-cluster-name-validation.yml, .github/workflows/test-slack-notify-result.yml
Otherwise, the `test` status check is not created if dependent jobs are failing
=> Add if: always() to test jobs with check-dependent-jobs steps

.github/workflows/test-oblt-cli-setup.yml, oblt-cli/setup/download.sh
It's just a minor improvement, but the second time the action is used, the execution time is reduced from 3s to 1s.
This will be fruitful if a workflow uses multiple oblt-cli/** commands in one job.
=> oblt-cli/setup: Skip downloading if file already exists

oblt-cli/run/action.yml
It's disabled by default on CI environments
=> oblt-cli/run: Remove `--disable-banner` flag

oblt-cli/run/action.yml
This helps keeping the flag even if the command is something like `cluster create || true`
=> oblt-cli/run: Move global flags before command

.github/workflows/no-test.yml, .github/workflows/test-oblt-cli-setup.yml, oblt-cli/setup/README.md, oblt-cli/setup/action.yml
this should help with ensuring no breaking changes can affect our consumers
There is a follow-up to bump the version with `updatecli`
=> oblt-cli/setup: Pin oblt-cli version

.github/workflows/no-test.yml, .github/workflows/test-aws-auth.yml, aws/auth/README.md, aws/auth/action.yml
Was successfully tested in https://github.com/elastic/apm-aws-lambda/actions/runs/9597412100/workflow?pr=491
=> Add aws/auth action

google/auth/action.yml
Probably `project-number` should be renamed for `project-id`... but regardless, the project-id was hardcoded but `project_number` was used somewhere else....
I'm not sure whether this is a bug.
=> fix(google/auth): honour the project-id input

aws/auth/README.md, buildkite/download-artifact/README.md, buildkite/run/README.md, check-dependent-jobs/README.md, git/setup/README.md, google/auth/README.md, oblt-cli/cluster-create-ccs/README.md, oblt-cli/cluster-create-custom/README.md, oblt-cli/cluster-create-serverless/README.md, oblt-cli/cluster-credentials/README.md, oblt-cli/cluster-destroy/README.md, oblt-cli/cluster-name-validation/README.md, oblt-cli/run/README.md, oblt-cli/setup/README.md, slack/notify-result/README.md, slack/send/README.md, snapshoty/run/README.md, updatecli/install/README.md, updatecli/run-and-notify/README.md, updatecli/run/README.md
Adds a badge like
that leads to github search code showing where the action is used
---
Example badge for `elastic/oblt-actions/aws/auth`: [![usages](https://img.shields.io/badge/usages-white?logo=githubactions&logoColor=blue)](https://github.com/search?q=elastic%2Foblt-actions%2Faws%2Fauth+%28path%3A.github%2Fworkflows+OR+path%3A**%2Faction.yml+OR+path%3A**%2Faction.yaml%29&type=code)
=> Add usage badges

google/auth/action.yml
This is not permitted by the YAML spec:
- https://yaml.org/spec/1.2-old/spec.html#id2777534
=> fix(google/auth): tabs are invalid

oblt-cli/run/action.yml
It is using the previous version
=> chore: bump oblt setup version

test-report/README.md, test-report/action.yml
Migrated from https://github.com/elastic/apm-pipeline-library/blob/main/.github/actions/test-report/action.yml
Tested at https://github.com/elastic/observability-robots-playground/pull/58/checks?check_run_id=29922269242
=> Add `test-report` action

.github/workflows/test-maven-await-artifact.yml, maven/await-artifact/README.md, maven/await-artifact/action.yml
See
https://github.com/elastic/apm-pipeline-library/tree/main/.github/actions/await-maven-artifact
I also renamed the inputs to use `-` as a separator and use env to help with [securing the thing](https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable)
=> feat(await-maven-artifact): migrate from https://github.com/elastic/apm-pipeline-library

.github/workflows/test-oblt-cli-cluster-create-custom.yml, .github/workflows/test-oblt-cli-cluster-create-serverless.yml, .github/workflows/test-oblt-cli-cluster-credentials.yml, .github/workflows/test-oblt-cli-create-ccs.yml, .github/workflows/test-oblt-cli-run.yml, .github/workflows/test-oblt-cli-setup.yml
Use the GitHub app to generate the required ephemeral tokens with the least permissive principle.
This is the very first attempt, there will be some follow-ups to update some of the remaining workflows.
* Finer-grained tokens with Service Machine accounts are required to rotate the secrets manually.
* GitHub app to generate temporary tokens is the advanced approach to avoid the above
* Document what the GH workflow requires to run in terms of access
* GitHub Token with Permissions does not trigger GitHub builds 
Use `tibdex/github-app-token` with the required permissions and the repository scope
Remove the `permissions` configuration in the GH workflow.
Configure the github-token with the ephemeral token
=> ci: use GitHub app for ephemeral tokens

maven/await-artifact/README.md, maven/await-artifact/action.yml
closes https://github.com/elastic/oblt-actions/issues/132
Support to query the maven central if `wait-for-maven-central` is set to `true` by default is not the case.
=> feat: support wait for maven central

.github/workflows/test-oblt-cli-undeploy-my-kibana.yml, oblt-cli/undeploy-my-kibana/README.md, oblt-cli/undeploy-my-kibana/action.yml
An initial attempt to move away from a finer-grained token and use ephemeral tokens.
It's difficult to migrate https://github.com/elastic/apm-pipeline-library/tree/main/.github/actions/undeploy-my-kibana to use the GH App ephemeral tokens.
It requires different permissions to access the members of a given org, so it can add an extra validation if the PR author is a member of Elastic.
I decided to remove that because it will require further complicated code, and the GitHub labels filtering in the workflows are good enough:
- https://github.com/elastic/kibana/blob/8d83a075f6228bb5a6e35a9bb4654fe29cee0cff/.github/workflows/undeploy-my-kibana.yml#L21
=> feat: undeploy-my-kibana

oblt-cli/undeploy-my-kibana/action.yml
Trying to solve 
```
with:
app_id: ***
private_key: ***
permissions: {
"contents": "read",
"issues": "write"
}
repositories: ["observability-test-environments"]
github_api_url: https://api.github.com
installation_retrieval_mode: repository
installation_retrieval_payload: elastic/kibana
revoke: true
Error: Could not create installation access token.
at createInstallationAccessToken (file:///home/runner/work/_actions/tibdex/github-app-token/3beb63f4bd073e614825[9](https://github.com/elastic/kibana/actions/runs/11223820283/job/31199282113?pr=195312#step:2:10)8c45c71c1019b59b73a/dist/main/index.js:9:86267)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async file:///home/runner/work/_actions/tibdex/github-app-token/3beb63f4bd073e61482598c45c71c[10](https://git …
```
=> fix: id installation

.github/workflows/test-oblt-cli-deploy-my-kibana.yml, .github/workflows/test-oblt-cli-undeploy-my-kibana.yml, oblt-cli/deploy-my-kibana/README.md, oblt-cli/deploy-my-kibana/action.yml, oblt-cli/undeploy-my-kibana/README.md
Replace https://github.com/elastic/apm-pipeline-library/tree/main/.github/actions/deploy-my-kibana with GitHub secrets and support only for no serverless.
Requires https://github.com/elastic/oblt-actions/pull/143
See https://github.com/elastic/oblt-actions/pull/59#issuecomment-2213186823
and a link to the GH private repository can be seen in this PR
=> feat(deploy-my-kibana): use github secrets

oblt-cli/run/README.md
The parameter is `github-token` instead of `token`
=> docs: rename parameter in example

.github/workflows/no-test.yml, .github/workflows/pre-commit.yml, .github/workflows/required-labels.yml, .github/workflows/test-aws-auth.yml, .github/workflows/test-buildkite-download-artifact.yml, .github/workflows/test-buildkite-run.yml, .github/workflows/test-check-dependent-jobs.yml, .github/workflows/test-elastic-active-branches.yml, .github/workflows/test-git-setup.yml, .github/workflows/test-github-comment-reaction.yml, .github/workflows/test-github-is-member-of.yml, .github/workflows/test-github-is-pr-author-member-of.yml, .github/workflows/test-google-auth.yml, .github/workflows/test-kibana-docker-image.yml, .github/workflows/test-maven-await-artifact.yml, .github/workflows/test-oblt-cli-cluster-create-custom.yml, .github/workflows/test-oblt-cli-cluster-create-serverless.yml, .github/workflows/test-oblt-cli-cluster-credentials.yml, .github/workflows/test-oblt-cli-cluster-name-validation.yml, .github/workflows/test-oblt-cli-create-ccs.yml, .github/workflows/test-oblt-cli-deploy-my-kibana.yml, .github/workflows/test-oblt-cli-run.yml, .github/workflows/test-oblt-cli-setup.yml, .github/workflows/test-oblt-cli-undeploy-my-kibana.yml, .github/workflows/test-slack-notify-result.yml, .github/workflows/test-slack-send.yml, .github/workflows/test-updatecli-run.yml, .github/workflows/test-version-framework.yml
Support for the merge-queue
We need to use an upstream branch when touching test workflows that require secrets
=> github-actions: support manual runs and merge-queue

updatecli/install/action.yml
The new version contains a breaking change for using dependsOn, source is not anymore the first task to run
> Sources were always executed before conditions and then targets.
https://github.com/updatecli/updatecli/releases/tag/v0.86.0
=> revert: use v2.68.0

.github/workflows/test-oblt-cli-deploy-my-kibana.yml
This should help with reducing the build times and creating leftovers for the `oblt-test-env`.
=> ci: avoid running often the deploy-my-kibana

.github/workflows/test-aws-auth.yml, aws/auth/README.md, aws/auth/action.yml
This will allow us to set up OIDC in a non-invasive way.
We have a complex workflow using reusable workflows, which uses multiple AWS credentials.
This way, we can pass the temporary credentials to the reusable workflow without changing the logic.
=> aws/auth: Pass outputs from upstream action to this action

.github/workflows/test-slack-send.yml, slack/send/action.yml
A regression when moving from `1.x` to `2.x` in https://github.com/elastic/oblt-actions/pull/164
Fixes issues when parsing the markdown:
I added a more comprehensive e2e test set to validate things work for more sophisticated slack notifications.
See
=> fix: slack send with multiline and special characters

.github/workflows/test-aws-auth.yml
Passing secrets https://github.com/elastic/oblt-actions/actions/runs/12083758738 from one job to another job doesn't 
work. (Passing it from one step to another should work though.)
For some reason, the dependent job was able to authenticate with empty aws-access-key-id and empty aws-secret-access-key. Not sure how it works though.
This will remove the secrets passing attempt in the test to avoid confusion or copypasta in the future.
=> Remove invalid test again

.github/workflows/test-slack-send.yml, slack/send/action.yml
Let's fix the issue when the message contains `"` 
See
=> fix: sanitise slack message

.github/workflows/test-elastic-active-branches.yml, elastic/active-branches/README.md, elastic/active-branches/action.yml, elastic/active-branches/script.py
Just a minor change to simplify consumers so they don't need to pass over those inputs
=> feat: set default values

.github/workflows/test-mergify-labels-copier.yml, mergify/labels-copier/README.md, mergify/labels-copier/action.yml, mergify/labels-copier/copy.sh
Took some bits and pieces from https://github.com/Mergifyio/gha-mergify-merge-queue-labels-copier
=> feat: support labels copier

mergify/labels-copier/README.md
No need to use `pull_request_target` anymore.
Need extra permissions:
- see https://github.com/cli/cli/issues/6274
=> docs: update permissions required

.github/workflows/test-oblt-cli-cluster-create-serverless.yml, oblt-cli/cluster-create-serverless/README.md, oblt-cli/cluster-create-serverless/action.yml
Similarly done in the past with https://github.com/elastic/oblt-actions/pull/226
* Support wait so it can be used in conjunction with `oblt-cli/cluster-credentials`
* Output the cluster-name
```yaml
- name: Get token
id: get_token
uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
with:
app_id: ${{ secrets.OBS_AUTOMATION_APP_ID }}
private_key: ${{ secrets.OBS_AUTOMATION_APP_PEM }}
permissions: >-
{
"contents": "write",
"pull_requests": "read",
"checks": "read"
}
repositories: >-
["observability-test-environments"]
- uses: elastic/oblt-actions/git/setup@v1
with:
github-token: ${{ steps.get_token.outputs.token }}
- name: Setup ephemeral cluster
uses: elastic/oblt-actions/oblt-cli/cluster-create-serverless@v1
id: cluster_create
with:
github-token: ${{ …
```
=> feat(serverless): support wait flag

github/backport-active/backport_script.py, github/backport-active/test_backport_script.py
see https://github.com/elastic/logstash/pull/17551#issuecomment-2802646405
Requires https://github.com/elastic/oblt-actions/pull/266
=> mergify: exclude 7.17 branch from backport-active-all

.ci/updatecli/values.d/scm.yml
See https://github.com/updatecli/policies/blob/8c4fd78886660c2500376d4f7ef7febbb7f38a29/updatecli/policies/autodiscovery/updatecli/values.yaml#L4-L5
So the automation with the changelog validation in the CI can works out of the box, otherwise https://github.com/elastic/oblt-actions/actions/runs/16436064616/job/46446167383?pr=318#step:5:12
=> updatecli: honour the labels for the automated changelog generator

.github/workflows/updatecli.yml
- No need for updatecli experimental anymore
- Run less often, `oblt-cli` is quite an active project, so we don't need to have one PR daily with a new version
- Replace tibdex/github-app-token with actions/create-github-app-token
See https://github.com/elastic/oblt-actions/actions/runs/16645650197
that created https://github.com/elastic/oblt-actions/pull/329
=> updatecli: use the new gh token, run weekly and remove experimental

.github/workflows/test-check-dependent-jobs.yml, check-dependent-jobs/README.md, check-dependent-jobs/action.yml
check-dependant-jobs is reporting a success if all the dependant jobs have a 'success' job.result.  This is causing issues when a job is skipped and the workflow succeed but still reports a failure in slack.
An example can be observed at https://github.com/elastic/apm-server/actions/runs/17391488346/job/49367574571
```
jobs: {
"run-upgrade": {
"result": "success",
"outputs": {}
},
"run-upgrade-bc": {
"result": "skipped",
"outputs": {}
},
"run-standalone": {
"result": "success",
"outputs": {}
}
}
```
Closes https://github.com/elastic/apm-server/issues/18400
credits to @ericywl for spotting the issue
=> feat: consider skipped job as success

.github/workflows/no-test.yml, .github/workflows/test-github-user-type.yml, github/user-type/action.yml
When a PR is opened by Copilot, the `github/user-type` action fails with a 404 error.
This is because the following API call fails with a 404
```bash
gh api -H "Accept: application/vnd.github+json" '/users/Copilot' 
```
The surprising part is that we have access to the same data when querying the pull-request (but this action can't as it uses the user login as input, not the PR).
For example with
```bash
gh api -H "Accept: application/vnd.github+json" '/repos/elastic/apm-agent-java/pulls/4221'  
```
We do get the user type from the returned JSON:
```json
{
"url": "https://api.github.com/repos/elastic/apm-agent-java/pulls/4221",
"id": 2843476620,
"node_id": "PR_kwDOBznsDs6pfAKM",
"html_url": "https://github.com/elastic/apm-agent-java/pull/4221",
"diff_url": …
```
=> github user type detection fix for Copilot

.github/workflows/test-git-setup.yml, .github/workflows/test-updatecli-install.yml, .github/workflows/test-updatecli-run.yml, .pre-commit-config.yaml
Use  https://github.com/rhysd/actionlint in the pre-commit
Fix linting defects
Comment out GitHub composite actions for now. Until we can validate things work as expected.
I ran ` pre-commit run --files elastic/active-branches/action.yml` and it reported
```
Validate GitHub Actions..................................................Failed
- hook id: check-github-actions
- exit code: 1
Schema validation errors were encountered.
elastic/active-branches/action.yml::$.inputs['exclude-branches']: Additional properties are not allowed ('type' was unexpected)
elastic/active-branches/action.yml::$.inputs['filter-branches'].default: False is not of type 'string'
elastic/active-branches/action.yml::$.inputs['filter-branches']: Additional properties are not allowed ('type' was unexpected) …
```
=> pre-commit: lint github actions
