.github/workflows/no-test.yml
Adds the `no-test / test` status check if no action folder source code is modified to satisfy required status checks.
=> Add test check if no action source code is touched

README.md
This is just a random change to be able to release `v1.0.0`
=> Release v1.0.0 without breaking changes

.github/workflows/no-test.yml, .github/workflows/test-buildkite-run.yml, buildkite/run/README.md, buildkite/run/action.yml, buildkite/run/run.sh, buildkite/run/wait-for.sh
Run bk pipelines using GitHub secrets
- Download artifacts will be done in a follow up in a different action
=> feat(buildkite): support buildkite run with wait-for

buildkite/download-artifact/README.md, buildkite/run/README.md, docs/CONTRIBUTING.md, git/setup/README.md, git/setup/action.yml, google/auth/README.md, oblt-cli/cluster-create-custom/README.md, oblt-cli/cluster-create-custom/action.yml, oblt-cli/cluster-create-serverless/README.md, oblt-cli/cluster-credentials/README.md, oblt-cli/cluster-name-validation/README.md, oblt-cli/cluster-name-validation/action.yml, oblt-cli/run/README.md, oblt-cli/run/action.yml, oblt-cli/setup/README.md, oblt-cli/setup/action.yml, slack/send/README.md, updatecli/install/README.md, updatecli/run-and-notify/README.md, updatecli/run-and-notify/action.yml, updatecli/run/README.md
Update README.md files using [gh-action-readme](https://github.com/reakaleek/gh-action-readme) GitHub CLI extension.
=> Update docs with gh-action-readme cli

.pre-commit-config.yaml, buildkite/download-artifact/README.md, buildkite/run/README.md, check-dependent-jobs/README.md, git/setup/README.md, google/auth/README.md, oblt-cli/cluster-create-ccs/README.md, oblt-cli/cluster-create-custom/README.md, oblt-cli/cluster-create-serverless/README.md, oblt-cli/cluster-credentials/README.md, oblt-cli/cluster-name-validation/README.md, oblt-cli/run/README.md, oblt-cli/setup/README.md, slack/notify-result/README.md, slack/send/README.md, snapshoty/run/README.md, updatecli/install/README.md, updatecli/run-and-notify/README.md, updatecli/run/README.md
This allows us to update the usage of all internal actions in a usage example.
=> Use new glob pattern feature of gh-action-readme@v0.4.0

oblt-cli/cluster-destroy/README.md, oblt-cli/cluster-destroy/action.yml
Also, don't set non-existing `slack-channel` input
=> Add missing username input

.github/dependabot.yml
- **Use dependabot wildcard directories**
- **Fix dependabot schedule**
=> Use dependabot wildcard directories

google/auth/action.yml
Reverts elastic/oblt-actions#67
=> Revert "fix(google/auth): honour the project-id input"

.github/workflows/test-elastic-active-branches.yml, elastic/active-branches/README.md, elastic/active-branches/action.yml, elastic/active-branches/script.py
copied from https://github.com/elastic/apm-pipeline-library/tree/main/.github/actions/elastic-stack-snapshot-branches
Do you think we should use this name?
=> feat: support active branches

github/validate-comment/README.md, github/validate-comment/action.yml
Replace https://github.com/elastic/apm-pipeline-library/tree/main/.github/actions/validate-github-comment
=> feat(github): validate-comment

.github/workflows/test-github-is-member-of.yml, github/is-member-of/README.md, github/is-member-of/action.yml
https://github.com/elastic/apm-pipeline-library-mp/tree/main/.github/actions/is-member-elastic-org
But use a generic flag to say what's the org
=> feat: migrate is-member-elastic-org 

.github/workflows/test-github-comment-reaction.yml, github/comment-reaction/README.md, github/comment-reaction/action.yml
migrate https://github.com/elastic/apm-pipeline-library/blob/main/.github/actions/comment-reaction/README.md
See https://github.com/elastic/oblt-actions/pull/59#issuecomment-2178560535
=> feat: github/comment-reaction

.github/workflows/test-version-framework.yml, version-framework/README.md, version-framework/action.yml, version-framework/matrix.py, version-framework/test-data/excluded.yml, version-framework/test-data/frameworks.yml, version-framework/test-data/versions.yml
Replace https://github.com/elastic/apm-pipeline-library/blob/main/.github/actions/version-framework
=> feat: replace apm-pipeline-library version-framework

.github/workflows/test-github-is-pr-author-member-of.yml, github/is-pr-author-member-of/README.md, github/is-pr-author-member-of/action.yml
Migrate https://github.com/elastic/apm-pipeline-library/blob/main/.github/actions/is-pr-author-member-elastic-org/README.md
=> feat: migrate is-pr-author-member-elastic-org@current

.github/workflows/required-labels.yml
I used https://github.com/mheap/github-action-required-labels/pull/84 and changed a bit
=> ci: support for merge_queue

.github/workflows/test-updatecli-run.yml, updatecli/install/README.md, updatecli/run-and-notify/README.md, updatecli/run-and-notify/action.yml, updatecli/run/README.md, updatecli/run/action.yml
Use https://github.com/elastic/oblt-actions/pull/176
=> feat: support version and version-file updatecli actions

elastic/active-branches/README.md, elastic/active-branches/action.yml, elastic/active-branches/script.py
This is optional and will help consumers who need to run something against those branches but those branches have not been created yet.
=> feat: support branches only active in the current repository

.github/workflows/test-elastic-active-branches.yml
=> test: add test coverage for the github action

oblt-cli/setup/download.sh
Trying to fix some environmental issues
=> feat: add retry if failing to download binary

.github/release-drafter.yml
closes https://github.com/elastic/oblt-actions/issues/35
=> chore: change headers for the categories

mergify/labels-copier/copy.sh
Closes https://github.com/elastic/oblt-actions/issues/233
=> fix: parsing th mergify PR

kibana-docker-image/build-and-push.sh
https://github.com/elastic/oblt-actions/blob/main/kibana-docker-image/build-and-push.sh
=> fix: skip-docker-ubuntu was removed

.github/workflows/no-test.yml, .github/workflows/test-elastic-validate-catalog.yml, elastic/validate-catalog/README.md, elastic/validate-catalog/action.yml
=> feat: validate catalog

.github/workflows/no-test.yml, .github/workflows/test-azure-auth.yml, azure/auth/README.md, azure/auth/action.yml
Adds azure auth workflow to interact with Azure resources using OIDC credentials.
=> feat(azure/login): first iteration

.github/workflows/no-test.yml, .github/workflows/test-github-changed-files.yml, .pre-commit-config.yaml, github/changed-files/README.md, github/changed-files/action.yml, github/changed-files/dist/index.js, github/changed-files/index.js, github/changed-files/index.test.js, github/changed-files/package.json
support a new output called `changed` to list all the files that were modified, deleted or added.
=> feat(changed-files): add changed output
